//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FORM_BSWApplication_Recommender
    {
        public string V1 { get; set; }
        public string V2 { get; set; }
        public string V3 { get; set; }
        public string V4 { get; set; }
        public string V5 { get; set; }
        public string V6 { get; set; }
        public string V7 { get; set; }
        public string V8 { get; set; }
        public string V9 { get; set; }
        public string V10 { get; set; }
        public string StudentNam_1_TEXT { get; set; }
        public string StudentNam_2_TEXT { get; set; }
        public string Recomender_1_TEXT { get; set; }
        public string Recomender_2_TEXT { get; set; }
        public string Recomender_3_TEXT { get; set; }
    }
}
