//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FORM_BSWApplication
    {
        public string V1 { get; set; }
        public string V2 { get; set; }
        public string V3 { get; set; }
        public string V4 { get; set; }
        public string V5 { get; set; }
        public string V6 { get; set; }
        public string V7 { get; set; }
        public string V8 { get; set; }
        public string V9 { get; set; }
        public string V10 { get; set; }
        public string Q1_1_TEXT { get; set; }
        public string Q1_2_TEXT { get; set; }
        public string Q1_3_TEXT { get; set; }
        public Nullable<System.DateTime> Q1_4_TEXT { get; set; }
        public string Q1_5_TEXT { get; set; }
        public string Q1_6_TEXT { get; set; }
        public string Q1_7_TEXT { get; set; }
        public string Q1_8_TEXT { get; set; }
        public string Q1_9_TEXT { get; set; }
        public string Q1_10_TEXT { get; set; }
        public string Q1_11_TEXT { get; set; }
        public string Gender { get; set; }
        public string Major { get; set; }
        public string Major_TEXT { get; set; }
        public string Classifica { get; set; }
        public string ReachAbroa { get; set; }
        public string Ethnic { get; set; }
        public string Ethnic_TEXT { get; set; }
        public string SocW205 { get; set; }
        public string SocW205_TEXT { get; set; }
        public string SocW206 { get; set; }
        public string SocW206_TEXT { get; set; }
        public string Stat { get; set; }
        public string Stat_TEXT { get; set; }
        public string Comp71Cred { get; set; }
        public string DblMaj { get; set; }
        public string DblMaj_TEXT { get; set; }
        public string C1VolList_1_TEXT { get; set; }
        public string C1VolList_2_TEXT { get; set; }
        public string C1VolList_3_TEXT { get; set; }
        public string C1VolList_4_TEXT { get; set; }
        public string C1VolList_5_TEXT { get; set; }
        public string C1VolExp { get; set; }
        public string C2VolList_1_TEXT { get; set; }
        public string C2VolList_2_TEXT { get; set; }
        public string C2VolList_3_TEXT { get; set; }
        public string C2VolList_4_TEXT { get; set; }
        public string C2VolList_5_TEXT { get; set; }
        public string C2VolExp { get; set; }
        public string C3VolList_1_TEXT { get; set; }
        public string C3VolList_2_TEXT { get; set; }
        public string C3VolList_3_TEXT { get; set; }
        public string C3VolList_4_TEXT { get; set; }
        public string C3VolList_5_TEXT { get; set; }
        public string C3VolExp { get; set; }
        public string C4VolList_1_TEXT { get; set; }
        public string C4VolList_2_TEXT { get; set; }
        public string C4VolList_3_TEXT { get; set; }
        public string C4VolList_4_TEXT { get; set; }
        public string C4VolList_5_TEXT { get; set; }
        public string C4VolExp { get; set; }
        public string C5VolList_1_TEXT { get; set; }
        public string C5VolList_2_TEXT { get; set; }
        public string C5VolList_3_TEXT { get; set; }
        public string C5VolList_4_TEXT { get; set; }
        public string C5VolList_5_TEXT { get; set; }
        public string C5VolExp { get; set; }
        public string C6VolList_1_TEXT { get; set; }
        public string C6VolList_2_TEXT { get; set; }
        public string C6VolList_3_TEXT { get; set; }
        public string C6VolList_4_TEXT { get; set; }
        public string C6VolList_5_TEXT { get; set; }
        public string C6VolExp { get; set; }
        public string SpecCircum { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
