//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FORM_BSWApplication_Recommendation
    {
        public string V1 { get; set; }
        public string V2 { get; set; }
        public string V3 { get; set; }
        public string V4 { get; set; }
        public string V5 { get; set; }
        public string V6 { get; set; }
        public string V7 { get; set; }
        public string V8 { get; set; }
        public string V9 { get; set; }
        public string V10 { get; set; }
        public string Student_FName { get; set; }
        public string Student_LName { get; set; }
        public string AnalyticalSkill { get; set; }
        public string WrittenCom { get; set; }
        public string OralCom { get; set; }
        public string Interpersonal { get; set; }
        public string Professionalism { get; set; }
        public string Resourceful { get; set; }
        public string InitiativeCreative { get; set; }
        public string SocialJusticeService { get; set; }
        public string OveralRec { get; set; }
        public string recLetter { get; set; }
        public string HowLong { get; set; }
        public string Capacity { get; set; }
    }
}
