//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssetLocation
    {
        public int RecID { get; set; }
        public Nullable<int> AssetID { get; set; }
        public Nullable<double> Location { get; set; }
        public Nullable<System.DateTime> DateChecked { get; set; }
    }
}
