//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContact_Log_Queue
    {
        public int contactQueueID { get; set; }
        public Nullable<System.DateTime> queuedDate { get; set; }
        public string toAddress { get; set; }
        public Nullable<int> contactTypeID { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> ADM_APPL_NUMBER { get; set; }
        public Nullable<int> TERM { get; set; }
        public string ExternalID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string queuedBy { get; set; }
    }
}
