//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEntityform
    {
        public int entityform_id { get; set; }
        public string type { get; set; }
        public string language { get; set; }
        public Nullable<int> created { get; set; }
        public Nullable<int> changed { get; set; }
        public byte[] data { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<short> draft { get; set; }
    }
}
