//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEntityForm_Data_PIVOT
    {
        public int entityform_id { get; set; }
        public string type { get; set; }
        public Nullable<int> created { get; set; }
        public Nullable<int> changed { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<short> draft { get; set; }
        public string field_1ftp_focusarea_firstchoice { get; set; }
        public string field_1ftp_focusarea_secondchoic { get; set; }
        public string field_1ftp_focusarea_thirdchoice { get; set; }
        public string field_are_you_fluent_in_any_lang { get; set; }
        public string field_as_part_of_this_program_do { get; set; }
        public string field_confirm_current_email { get; set; }
        public string field_confirm_ftp { get; set; }
        public string field_confirm_phone_number { get; set; }
        public string field_confirm_ptp { get; set; }
        public string field_confirm_signature { get; set; }
        public string field_current_program { get; set; }
        public string field_declaration_focus { get; set; }
        public string field_declaration_site { get; set; }
        public string field_do_school_social_worker { get; set; }
        public string field_do_you_have_a_safe_reliabl { get; set; }
        public string field_do_you_have_a_valid_driver { get; set; }
        public string field_do_you_have_a_violation_on { get; set; }
        public string field_do_you_intend_to_be_employ { get; set; }
        public string field_do_you_intend_to_complete_ { get; set; }
        public string field_do_you_plan_of_having_paid { get; set; }
        public string field_do_you_plan_on_applying_fo { get; set; }
        public string field_do_you_plan_to_apply_to_us { get; set; }
        public string field_exp_400_credits { get; set; }
        public string field_exp_400_date { get; set; }
        public string field_exp_400_grade { get; set; }
        public string field_exp_400_uni { get; set; }
        public string field_exp_400_uni_code { get; set; }
        public string field_exp_401_credits { get; set; }
        public string field_exp_401_date { get; set; }
        public string field_exp_401_grade { get; set; }
        public string field_exp_401_uni { get; set; }
        public string field_exp_401_uni_code { get; set; }
        public string field_exp_441_credits { get; set; }
        public string field_exp_441_date { get; set; }
        public string field_exp_441_grade { get; set; }
        public string field_exp_441_uni { get; set; }
        public string field_exp_441_uni_code { get; set; }
        public string field_exp_442_credits { get; set; }
        public string field_exp_442_date { get; set; }
        public string field_exp_442_grade { get; set; }
        public string field_exp_442_uni { get; set; }
        public string field_exp_442_uni_code { get; set; }
        public string field_exp_605_uni_code { get; set; }
        public string field_exp_606_credits { get; set; }
        public string field_exp_606_date { get; set; }
        public string field_exp_606_grade { get; set; }
        public string field_exp_606_uni { get; set; }
        public string field_exp_606_uni_code { get; set; }
        public string field_exp_612_credits { get; set; }
        public string field_exp_612_date { get; set; }
        public string field_exp_612_grade { get; set; }
        public string field_exp_612_uni { get; set; }
        public string field_exp_612_uni_code { get; set; }
        public string field_exp_640_credits { get; set; }
        public string field_exp_640_date { get; set; }
        public string field_exp_640_equiv { get; set; }
        public string field_exp_640_grade { get; set; }
        public string field_exp_640_syllabus { get; set; }
        public string field_exp_640_uni { get; set; }
        public string field_exp_640_uni_code { get; set; }
        public string field_exp_650_credits { get; set; }
        public string field_exp_650_date { get; set; }
        public string field_exp_650_equiv { get; set; }
        public string field_exp_650_grade { get; set; }
        public string field_exp_650_syllabus { get; set; }
        public string field_exp_650_uni { get; set; }
        public string field_exp_650_uni_code { get; set; }
        public string field_exp_711_credits { get; set; }
        public string field_exp_711_date { get; set; }
        public string field_exp_711_grade { get; set; }
        public string field_exp_711_uni { get; set; }
        public string field_exp_711_uni_code { get; set; }
        public string field_exp_list { get; set; }
        public string field_exp_statistics { get; set; }
        public string field_exp_stats_credits { get; set; }
        public string field_exp_stats_date { get; set; }
        public string field_exp_stats_equiv { get; set; }
        public string field_exp_stats_grade { get; set; }
        public string field_exp_stats_syllabus { get; set; }
        public string field_exp_stats_uni { get; set; }
        public string field_exp_stats_uni_code { get; set; }
        public string field_field_exp_605_credits { get; set; }
        public string field_field_exp_605_date { get; set; }
        public string field_field_exp_605_grade { get; set; }
        public string field_field_exp_605_uni { get; set; }
        public string field_fieldgeographic_pref { get; set; }
        public string field_fieldpref_maxtraveldist { get; set; }
        public string field_for_the_next_fall_term_i_w { get; set; }
        public string field_ftp_focusarea_firstchoice { get; set; }
        public string field_ftp_focusarea_secondchoice { get; set; }
        public string field_ftp_focusarea_thirdchoice { get; set; }
        public string field_have_you_completed_a_field { get; set; }
        public string field_international_placement { get; set; }
        public string field_language_name_1 { get; set; }
        public string field_language_name_2 { get; set; }
        public string field_language_profeciency_1 { get; set; }
        public string field_language_profeciency_2 { get; set; }
        public string field_msw_transcripts { get; set; }
        public string field_mswce_confirm1 { get; set; }
        public string field_mswce_confirm2 { get; set; }
        public string field_mswce_confirm3 { get; set; }
        public string field_mswce_confirm4 { get; set; }
        public string field_mswce_confirm5 { get; set; }
        public string field_mswce_date { get; set; }
        public string field_mswce_signature { get; set; }
        public string field_name_of_your_field_faculty { get; set; }
        public string field_paid_exp { get; set; }
        public string field_phdprog_advisor_email { get; set; }
        public string field_phdprog_advisor_name { get; set; }
        public string field_phdprog_course_work { get; set; }
        public string field_phdprog_currentfunding { get; set; }
        public string field_phdprog_currentjobmarket { get; set; }
        public string field_phdprog_dissertation_def { get; set; }
        public string field_phdprog_dissertation_prop { get; set; }
        public string field_phdprog_dissertator_status { get; set; }
        public string field_phdprog_goals { get; set; }
        public string field_phdprog_graduation { get; set; }
        public string field_phdprog_incomplete { get; set; }
        public string field_phdprog_nextyear_funding { get; set; }
        public string field_phdprog_prelim_exam { get; set; }
        public string field_phdprog_prelim_proposal { get; set; }
        public string field_phdprog_presentations { get; set; }
        public string field_phdprog_publications { get; set; }
        public string field_phdprog_teaching_experienc { get; set; }
        public string field_phdprog_upcomingjobmarket { get; set; }
        public string field_phdprog_what_progress { get; set; }
        public string field_placement_uncomfortable { get; set; }
        public string field_plagiarism_date { get; set; }
        public string field_plagiarism_signature { get; set; }
        public string field_please_choose_your_first_c { get; set; }
        public string field_previous_field_unit_ { get; set; }
        public string field_recent_placement_exp { get; set; }
        public string field_req_field_hours { get; set; }
        public string field_req_field_hours_explain { get; set; }
        public string field_resume { get; set; }
        public string field_signature { get; set; }
        public string field_signature_date { get; set; }
        public string field_srr_date { get; set; }
        public string field_srr_signature { get; set; }
        public string field_srr_student_resp_confirm { get; set; }
        public string field_srr_student_rights_confirm { get; set; }
        public string field_street_address { get; set; }
        public string field_student_address_city { get; set; }
        public string field_student_address_state { get; set; }
        public string field_student_address_zip_code { get; set; }
        public string field_student_cell { get; set; }
        public string field_student_home_phone { get; set; }
        public string field_student_work_phone { get; set; }
        public string field_sw_areas_field { get; set; }
        public string field_traveloutdane { get; set; }
        public string field_upcoming_enrollment { get; set; }
        public string field_what_type_of_transportatio { get; set; }
        public string field_which_of_the_prior_phone_n { get; set; }
        public string field_you_indicated_that_you_hav { get; set; }
    }
}
