//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEntityform_alldata
    {
        public string fieldName { get; set; }
        public string bundle { get; set; }
        public int entity_id { get; set; }
        public string fieldValue { get; set; }
    }
}
