//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGrad_COMPLETION_DETAILS
    {
        public int EMPLID { get; set; }
        public int TERM { get; set; }
        public string CHECKLIST_ITEM { get; set; }
        public string RECEIVED { get; set; }
        public string PORTAL_NOTE { get; set; }
        public string INTERNAL_NOTE { get; set; }
        public Nullable<double> COLORDER { get; set; }
    }
}
