//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGrad_APPS
    {
        public int ID { get; set; }
        public string ID_String { get; set; }
        public string CAMPUS_ID { get; set; }
        public string FINAIDS_INTEREST { get; set; }
        public string STDNT_GROUP { get; set; }
        public string LAST_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string EMAILID { get; set; }
        public string MAIL_ADDRESS_LINE1 { get; set; }
        public string MAIL_ADDRESS_LINE2 { get; set; }
        public string MAIL_ADDRESS_LINE3 { get; set; }
        public string MAIL_ADDRESS_LINE4 { get; set; }
        public string MAIL_CITY { get; set; }
        public string MAIL_STATE { get; set; }
        public string MAIL_POSTAL { get; set; }
        public string MAIL_COUNTRY { get; set; }
        public string MAIL_COUNTRY_DESC { get; set; }
        public string MAIL_PHONE { get; set; }
        public string MAIL_EXTENSION { get; set; }
        public string HOME_ADDRESS_LINE1 { get; set; }
        public string HOME_ADDRESS_LINE2 { get; set; }
        public string HOME_ADDRESS_LINE3 { get; set; }
        public string HOME_ADDRESS_LINE4 { get; set; }
        public string HOME_CITY { get; set; }
        public string HOME_STATE { get; set; }
        public string HOME_POSTAL { get; set; }
        public string HOME_COUNTRY { get; set; }
        public string HOME_COUNTRY_DESC { get; set; }
        public string HOME_PHONE { get; set; }
        public string HOME_EXTENSION { get; set; }
        public string SEX { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public string MILITARY_STATUS { get; set; }
        public string CITIZENSHIP_STATUS { get; set; }
        public string CITIZENSHIP_COUNTRY { get; set; }
        public string ETHNIC { get; set; }
        public string ETHNIC_DESCRIPTION { get; set; }
        public string ETHNIC_DETAIL { get; set; }
        public string ETHNIC_DETAIL_DESCR { get; set; }
        public int ADM_APPL_NUMBER { get; set; }
        public Nullable<System.DateTime> ADM_CREATION_DATE { get; set; }
        public int ADMIT_TERM { get; set; }
        public string ACAD_PROG { get; set; }
        public string ACAD_PROG_DESC { get; set; }
        public string ACAD_PLAN { get; set; }
        public string ACAD_SUBPLAN { get; set; }
        public string ACAD_SUBPLAN_DESCR { get; set; }
        public string ACAD_LOAD_APPR { get; set; }
        public string COUNTRY_OF_BIRTH { get; set; }
        public string COUNTRY_NAME { get; set; }
        public string RESIDENCY { get; set; }
        public string SELF_REPORTED_GPA { get; set; }
        public string VISA_TYPE { get; set; }
        public Nullable<System.DateTime> VISA_PERMIT_DATE { get; set; }
        public string ADM_APPL_METHOD { get; set; }
        public string ADMIT_TYPE { get; set; }
        public string APPL_FEE_STATUS { get; set; }
        public string APPL_FEE_STATUS_DESCR { get; set; }
        public Nullable<System.DateTime> LOADDATE { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
