//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLookupCourse_ORDER
    {
        public int OID { get; set; }
        public int progID { get; set; }
        public string SUBJECT_CODE { get; set; }
        public string CATALOG_NUMBER { get; set; }
        public int ORDER_NUMBER { get; set; }
        public bool lockShow { get; set; }
        public Nullable<int> focusArea { get; set; }
        public Nullable<int> courseGroupID { get; set; }
    
        public virtual tblLookupCourse_Group tblLookupCourse_Group { get; set; }
    }
}
