//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLookupContact_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLookupContact_Type()
        {
            this.tblContact_Log = new HashSet<tblContact_Log>();
        }
    
        public int contactTypeID { get; set; }
        public string contactName { get; set; }
        public string contactDescription { get; set; }
        public bool isMSWFinalDecision { get; set; }
        public Nullable<bool> isMSWFTAccept { get; set; }
        public Nullable<bool> isMSWPTAccept { get; set; }
        public bool isMSWAdmissionLetter { get; set; }
        public bool isBSWFinalDecision { get; set; }
        public bool isBSWAdmissionLetter { get; set; }
        public bool isPHDFinalDecision { get; set; }
        public bool isPHDAdmissionLetter { get; set; }
        public bool isExemptionTemplate { get; set; }
        public bool canAddQueue { get; set; }
        public string functionToRun { get; set; }
        public string templateLoc { get; set; }
        public string contactNote { get; set; }
        public byte[] upsize_ts { get; set; }
        public bool canLog { get; set; }
        public Nullable<bool> editAdvisor { get; set; }
        public Nullable<bool> editField { get; set; }
        public Nullable<bool> editAny { get; set; }
        public Nullable<bool> editAdmission { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblContact_Log> tblContact_Log { get; set; }
    }
}
