//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLookupFlag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLookupFlag()
        {
            this.tblSTDNT_FLAG = new HashSet<tblSTDNT_FLAG>();
        }
    
        public int flagID { get; set; }
        public string flagTitle { get; set; }
        public string flagDesc { get; set; }
        public bool isSystemFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSTDNT_FLAG> tblSTDNT_FLAG { get; set; }
    }
}
