//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrg
    {
        public int OrgID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string OrgName { get; set; }
        public string PreviousName { get; set; }
        public string Address { get; set; }
        public string POBox { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string County { get; set; }
        public string Phone { get; set; }
        public string Phone_ext { get; set; }
        public string Website { get; set; }
        public string Focus { get; set; }
        public string StudentActivities { get; set; }
        public string PreferredStudentSchedule { get; set; }
        public string AverageNumberstudents { get; set; }
        public string StudentType { get; set; }
        public string StudentDiscipline { get; set; }
        public string EveningWeekendHours { get; set; }
        public string Busline { get; set; }
        public string Vehicle { get; set; }
        public string SupervisorNamesEmailPhoneCredential { get; set; }
        public string QuestionnaireComments { get; set; }
        public Nullable<System.DateTime> LastEmail { get; set; }
        public Nullable<System.DateTime> LastEmailResponse { get; set; }
        public bool CoveredParentAffAgreement { get; set; }
        public string AffiliationNotes { get; set; }
        public bool FlaggedDirector { get; set; }
        public string FieldDirectorComments { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> OrgAdded { get; set; }
        public Nullable<System.DateTime> OrgUpdate { get; set; }
        public bool FTP { get; set; }
        public bool PTP { get; set; }
    }
}
