//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReview
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblReview()
        {
            this.tblReview_Email = new HashSet<tblReview_Email>();
        }
    
        public int ReviewID { get; set; }
        public Nullable<int> ReviewerID { get; set; }
        public Nullable<int> ADM_APPL_NUMBER { get; set; }
        public Nullable<int> TERM { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> program { get; set; }
        public Nullable<int> ID { get; set; }
        public string V1 { get; set; }
        public string V5 { get; set; }
        public Nullable<int> RTID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReview_Email> tblReview_Email { get; set; }
    }
}
