//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReviewTeam
    {
        public int JID { get; set; }
        public int ReviewerID { get; set; }
        public int MatchReviewerID { get; set; }
        public bool canWork { get; set; }
    }
}
