//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReview_Email
    {
        public int RID { get; set; }
        public Nullable<int> ReviewID { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
    
        public virtual tblReview tblReview { get; set; }
    }
}
