//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSTDNT_COURSES
    {
        public int TERM { get; set; }
        public int ID { get; set; }
        public Nullable<double> CAMPUS_ID { get; set; }
        public string COURSE_ID { get; set; }
        public string SUBJECT_CODE { get; set; }
        public string CATALOG_NUMBER { get; set; }
        public decimal COURSE_OFFER_NUMBER { get; set; }
        public string SESSION_CODE { get; set; }
        public Nullable<int> CREDITS_TAKEN { get; set; }
        public string OFFICIAL_GRADE { get; set; }
        public string COURSE_SECTION_RANGE1 { get; set; }
        public string COURSE_SECTION_RANGE2 { get; set; }
        public string COURSE_SECTION_RANGE3 { get; set; }
        public string COMBINATION_TYPE { get; set; }
        public string PRIMARY_SUBJECT_CODE { get; set; }
        public string PRIMARY_CATALOG_NUMBER { get; set; }
        public Nullable<System.DateTime> EXTRACT_DATE_TIME { get; set; }
        public string Academic_Level { get; set; }
    }
}
