//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSTDNT_DIRECTORY
    {
        public double TERM { get; set; }
        public double ID { get; set; }
        public Nullable<double> CAMPUS_ID { get; set; }
        public string NAME { get; set; }
        public string NAME_LAST_PREFERRED { get; set; }
        public string NAME_FIRST_PREFERRED { get; set; }
        public string NAME_MIDDLE_PREFERRED { get; set; }
        public bool FERPA_FLAG { get; set; }
        public bool HOLD_POSTAL_IND { get; set; }
        public bool HOLD_EMAIL_IND { get; set; }
        public bool WITHDREW_IND { get; set; }
        public string HOME_ADDRESS_LINE1 { get; set; }
        public string HOME_ADDRESS_LINE2 { get; set; }
        public string HOME_ADDRESS_LINE3 { get; set; }
        public string HOME_ADDRESS_LINE4 { get; set; }
        public string HOME_CITY { get; set; }
        public string HOME_STATE { get; set; }
        public string HOME_COUNTY { get; set; }
        public string HOME_ZIP_CODE { get; set; }
        public string HOME_COUNTRY_CODE { get; set; }
        public string HOME_COUNTRY_DESCR { get; set; }
        public string HOME_PHONE1 { get; set; }
        public string HOME_EXTENSION1 { get; set; }
        public string HOME_PHONE2 { get; set; }
        public string HOME_EXTENSION2 { get; set; }
        public string HOME_FAX { get; set; }
        public string MAIL_ADDRESS_LINE1 { get; set; }
        public string MAIL_ADDRESS_LINE2 { get; set; }
        public string MAIL_ADDRESS_LINE3 { get; set; }
        public string MAIL_ADDRESS_LINE4 { get; set; }
        public string MAIL_CITY { get; set; }
        public string MAIL_STATE { get; set; }
        public string MAIL_COUNTY { get; set; }
        public string MAIL_ZIP_CODE { get; set; }
        public string MAIL_COUNTRY_CODE { get; set; }
        public string MAIL_COUNTRY_DESCR { get; set; }
        public string MAIL_PHONE1 { get; set; }
        public string MAIL_EXTENSION1 { get; set; }
        public string MAIL_PHONE2 { get; set; }
        public string MAIL_EXTENSION2 { get; set; }
        public string MAIL_FAX { get; set; }
        public string PREFERRED_PHONE { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public Nullable<double> AGE { get; set; }
        public Nullable<System.DateTime> EXTRACT_DATE_TIME { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
