//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSTDNT_LOCAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSTDNT_LOCAL()
        {
            this.tblSTDNT_Address = new HashSet<tblSTDNT_Address>();
            this.tblSTDNT_COURSES_EXEMPTIONS = new HashSet<tblSTDNT_COURSES_EXEMPTIONS>();
            this.tblSTDNT_COURSES_GroupOveride = new HashSet<tblSTDNT_COURSES_GroupOveride>();
            this.tblSTDNT_COURSES_NOTE = new HashSet<tblSTDNT_COURSES_NOTE>();
            this.tblSTDNT_FLAG = new HashSet<tblSTDNT_FLAG>();
            this.tblSTDNT_PLAN = new HashSet<tblSTDNT_PLAN>();
        }
    
        public int PID { get; set; }
        public Nullable<double> StudentID { get; set; }
        public int ID { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string PrevLName { get; set; }
        public string MName { get; set; }
        public bool SpecialNeeds { get; set; }
        public string SpecialNeedsNotes { get; set; }
        public Nullable<int> SWMailbox { get; set; }
        public string CurrentStreet { get; set; }
        public string CurrentCity { get; set; }
        public string CurrentState { get; set; }
        public string CurrentZip { get; set; }
        public string SummerContactYear { get; set; }
        public string SummerStreet { get; set; }
        public string SummerCity { get; set; }
        public string SummerState { get; set; }
        public string SummerZip { get; set; }
        public string PermanentStreet { get; set; }
        public string PermanentCity { get; set; }
        public string PermanentState { get; set; }
        public string PermanentZip { get; set; }
        public string CellPhone { get; set; }
        public string WorkPhone { get; set; }
        public string WorkPhoneExtension { get; set; }
        public string HomePhone { get; set; }
        public string HomePhoneExtension { get; set; }
        public string PermanentPhone { get; set; }
        public string PermanentPhoneExtension { get; set; }
        public string SummerPhone { get; set; }
        public string SummerPhoneExtension { get; set; }
        public bool WIBackgroundComp { get; set; }
        public string WIBackgroundCheckYear { get; set; }
        public bool WIDiscrepancy { get; set; }
        public bool OOSBackgroundComp { get; set; }
        public string OOSBackgroundCheckYear { get; set; }
        public bool OOSDiscrepancy { get; set; }
        public string OOSBackgroundCheckState { get; set; }
        public string BackgroundCheckComment { get; set; }
        public string AlumniTitle { get; set; }
        public string AlumniCompany { get; set; }
        public string CurrentEmployment_1 { get; set; }
        public string CurrentEmployment_2 { get; set; }
        public string CurrentEmploymentAddress { get; set; }
        public bool IVE_Student { get; set; }
        public string IVE_EMail { get; set; }
        public string IVE_Phone1 { get; set; }
        public string IVE_Phone2 { get; set; }
        public string PreviousEmployer { get; set; }
        public Nullable<double> NumberOfyears { get; set; }
        public string Comments { get; set; }
        public string TypeofEmployment { get; set; }
        public Nullable<System.DateTime> StudentAdded { get; set; }
        public Nullable<System.DateTime> StudentUpdated { get; set; }
        public string VetranStatus { get; set; }
        public string Exemptions { get; set; }
        public string GridInfo { get; set; }
        public Nullable<int> PT_StudentGroup { get; set; }
        public bool AdvSt { get; set; }
        public int FocusArea { get; set; }
        public string studentPhotoLoc { get; set; }
        public Nullable<int> currentProgram { get; set; }
        public bool isSchoolSocialWork { get; set; }
        public string resCounty { get; set; }
        public string ID_String { get; set; }
        public Nullable<int> MSW_Ant_GradTerm { get; set; }
        public bool isProspective { get; set; }
        public System.DateTime FocusAreaUpdated { get; set; }
        public byte[] upsized_ts { get; set; }
    
        public virtual tblAdvisor_Note tblAdvisor_Note { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSTDNT_Address> tblSTDNT_Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSTDNT_COURSES_EXEMPTIONS> tblSTDNT_COURSES_EXEMPTIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSTDNT_COURSES_GroupOveride> tblSTDNT_COURSES_GroupOveride { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSTDNT_COURSES_NOTE> tblSTDNT_COURSES_NOTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSTDNT_FLAG> tblSTDNT_FLAG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSTDNT_PLAN> tblSTDNT_PLAN { get; set; }
    }
}
