//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSTDNT_TIMETABLE
    {
        public Nullable<double> TERM { get; set; }
        public string SESSION_CODE { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string WEEKS_OF_INSTRUCTION { get; set; }
        public string SUBJECT_CODE { get; set; }
        public string SUBJECT_DESCR { get; set; }
        public string CATALOG_NUMBER { get; set; }
        public string COURSE_TITLE { get; set; }
        public string ACADEMIC_ORG { get; set; }
        public string COURSE_ACADEMIC_GROUP { get; set; }
        public string COURSE_ID { get; set; }
        public string SECTION_NUMBER { get; set; }
        public string COMBINED_SECTION_IND { get; set; }
        public string COMBINED_SECTIONS_ID { get; set; }
        public string COMPONENT_TYPE { get; set; }
        public string OPTIONAL_SECTION_IND { get; set; }
        public string BEGIN_TIME { get; set; }
        public string END_TIME { get; set; }
        public Nullable<decimal> CLASS_LENGTH { get; set; }
        public Nullable<decimal> NUMBER_OF_DAYS { get; set; }
        public string STANDARD_MEETING_PATTERN { get; set; }
        public string MEETS_MON_IND { get; set; }
        public string MEETS_TUES_IND { get; set; }
        public string MEETS_WED_IND { get; set; }
        public string MEETS_THURS_IND { get; set; }
        public string MEETS_FRI_IND { get; set; }
        public string MEETS_SAT_IND { get; set; }
        public string MEETS_SUN_IND { get; set; }
        public string INSTRUCTION_MODE { get; set; }
        public string INSTRUCTION_MODE_DESCR { get; set; }
        public string FACILITY_ID { get; set; }
        public string BUILDING_NAME { get; set; }
        public string ROOM_NUMBER { get; set; }
        public Nullable<decimal> ROOM_CAP_REQUEST { get; set; }
        public Nullable<decimal> ROOM_SEATING_CAPACITY { get; set; }
        public Nullable<decimal> ASSOCIATED_CLASS { get; set; }
        public Nullable<decimal> CLASS_MEETING_NUMBER { get; set; }
        public Nullable<decimal> COMPONENT_COUNT { get; set; }
        public Nullable<decimal> COURSE_OFFER_NUMBER { get; set; }
        public Nullable<decimal> TOPIC_TITLE_NUMBER { get; set; }
        public string TOPIC_TITLE_DESCR { get; set; }
        public string INSTRUCTOR_ID { get; set; }
        public string INSTRUCTOR_NAME { get; set; }
        public string INSTRUCTOR_ROLE_CODE { get; set; }
        public string INSTRUCTOR_ROLE_DESCR { get; set; }
        public string COURSE_ADMINISTRATOR_ID { get; set; }
        public string COURSE_ADMINISTRATOR_NAME { get; set; }
        public string COMBINATION_TYPE { get; set; }
        public string PRIMARY_OR_SECONDARY_DEPT { get; set; }
        public string PRIMARY_SUBJECT_CODE { get; set; }
        public string PRIMARY_SESSION_CODE { get; set; }
        public string PRIMARY_CATALOG_NUMBER { get; set; }
        public string PRIMARY_SECTION_NUMBER { get; set; }
        public Nullable<decimal> CLASS_NUMBER { get; set; }
        public Nullable<decimal> ENROLLMENT_CAP { get; set; }
        public Nullable<decimal> COMBINED_ROOM_CAP_REQUEST { get; set; }
        public Nullable<decimal> COMBINED_ENROLLMENT { get; set; }
        public Nullable<decimal> COMBINED_ENROLLMENT_CAP { get; set; }
        public Nullable<decimal> SECTION_COUNT { get; set; }
        public Nullable<decimal> WAIT_LIST_TOT { get; set; }
        public Nullable<decimal> WAIT_LIST_CAP { get; set; }
        public Nullable<decimal> COMBINED_WAIT_LIST_TOT { get; set; }
        public Nullable<decimal> COMBINED_WAIT_LIST_CAP { get; set; }
        public Nullable<System.DateTime> EXTRACT_DATE_TIME { get; set; }
        public string keyID { get; set; }
    }
}
