//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSTDNT
    {
        public int PID { get; set; }
        public int TERM { get; set; }
        public int ID { get; set; }
        public Nullable<double> CAMPUS_ID { get; set; }
        public string NAME { get; set; }
        public bool FERPA_FLAG { get; set; }
        public bool DECEASED_IND { get; set; }
        public bool WITHDREW_IND { get; set; }
        public string WITHDREW_REASON { get; set; }
        public Nullable<System.DateTime> WITHDREW_DATE { get; set; }
        public string PRIMARY_ACADEMIC_GROUP { get; set; }
        public string ACADEMIC_LEVEL { get; set; }
        public string ACADEMIC_LEVEL_PROJ { get; set; }
        public string ACADEMIC_LEVEL_EOT { get; set; }
        public string CAREER_TYPE { get; set; }
        public string CAREER { get; set; }
        public string GENDER { get; set; }
        public Nullable<decimal> AGE { get; set; }
        public bool CITIZEN_IND { get; set; }
        public string CITIZEN_STATUS { get; set; }
        public string RESIDENCY { get; set; }
        public string TUITION_RESIDENCY { get; set; }
        public string VISA_PERMIT_TYPE { get; set; }
        public string VISA_PERMIT_NUMBER { get; set; }
        public string COUNTRY_OF_CITIZENSHIP { get; set; }
        public string COUNTRY_OF_CITIZENSHIP_DESCR { get; set; }
        public string COUNTRY_OF_BIRTH { get; set; }
        public string COUNTRY_OF_BIRTH_DESCR { get; set; }
        public string PRIMARY_SUPPORT_DESCR { get; set; }
        public string SECONDARY_SUPPORT_DESCR { get; set; }
        public string MARITAL_STATUS_DESCR { get; set; }
        public bool VETERAN_STATUS { get; set; }
        public string DIVERSITY { get; set; }
        public string DIVERSITY_DESCR { get; set; }
        public string ETHNIC_GROUP { get; set; }
        public string ETHNIC_GROUP_DESCR { get; set; }
        public Nullable<short> MINORITY { get; set; }
        public bool TARGETED_MINORITY { get; set; }
        public string ACADEMIC_LOAD { get; set; }
        public string ADMIT_TYPE { get; set; }
        public string ACADEMIC_ADVANCEMENT_PROG { get; set; }
        public string DISSERTATOR_IND { get; set; }
        public string HIGH_SCHOOL_CODE { get; set; }
        public string HIGH_SCHOOL_PERCENTILE { get; set; }
        public string MATRICULATION_TERM { get; set; }
        public string DEG_EXPECTED { get; set; }
        public Nullable<double> TERM_CREDITS_TOTAL { get; set; }
        public Nullable<double> TERM_TAKEN_CREDITS_TOTAL { get; set; }
        public Nullable<double> TERM_TAKEN_CREDITS_GPA { get; set; }
        public Nullable<double> TERM_TAKEN_CREDITS_NOGPA { get; set; }
        public Nullable<double> TERM_TAKEN_CREDITS_PROGRESS { get; set; }
        public Nullable<double> TERM_TAKEN_CREDITS_PROG_GRAD { get; set; }
        public Nullable<double> TERM_INPROG_CREDITS_TOTAL { get; set; }
        public Nullable<double> TERM_INPROG_CREDITS_GPA { get; set; }
        public Nullable<double> TERM_INPROG_CREDITS_NOGPA { get; set; }
        public Nullable<double> TERM_CREDITS_AUDIT { get; set; }
        public Nullable<double> TERM_GRADE_POINTS { get; set; }
        public Nullable<double> TERM_GPA { get; set; }
        public Nullable<double> CUM_CREDITS_TOTAL { get; set; }
        public Nullable<double> CUM_TAKEN_CREDITS_GPA { get; set; }
        public Nullable<double> CUM_TRANSFER_CREDITS { get; set; }
        public Nullable<double> CUM_TEST_CREDITS { get; set; }
        public Nullable<double> CUM_OTHER_CREDITS { get; set; }
        public Nullable<double> CUM_GRADE_POINTS { get; set; }
        public Nullable<double> CUM_GPA { get; set; }
        public Nullable<double> PREVIOUS_TERM_GPA { get; set; }
        public Nullable<double> PREVIOUS_GPA_TERM { get; set; }
        public Nullable<short> NEGATIVE_SERVICE_IND { get; set; }
        public string SEMESTER_HONORS1 { get; set; }
        public string SEMESTER_HONORS2 { get; set; }
        public Nullable<System.DateTime> EXTRACT_DATE_TIME { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
