//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int RecID { get; set; }
        public string LoginID { get; set; }
        public bool isAdmin { get; set; }
        public bool isSysAdmin { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<int> TimesOpenedProgram { get; set; }
        public bool DenyAccess { get; set; }
        public bool canEditStudent { get; set; }
        public bool isFieldUser { get; set; }
        public bool isAdmissionUser { get; set; }
        public bool isAdvisor { get; set; }
        public bool searchAsType { get; set; }
        public string userEmail { get; set; }
    }
}
