//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Placement_Single_View
    {
        public int ID { get; set; }
        public int TERM { get; set; }
        public string OrgName { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string WorkPhone { get; set; }
        public string Email { get; set; }
        public int SPID { get; set; }
        public int OrgID { get; set; }
    }
}
