//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Program_Courses_OutProgram
    {
        public Nullable<int> ID { get; set; }
        public string SUBJECT_CODE { get; set; }
        public string CATALOG_NUMBER { get; set; }
        public int ORDER_NUMBER { get; set; }
        public string TERM { get; set; }
        public Nullable<int> CREDITS_TAKEN { get; set; }
        public string OFFICIAL_GRADE { get; set; }
        public Nullable<int> NID { get; set; }
        public string Course_Note { get; set; }
        public string Academic_Level { get; set; }
        public int courseGroupID { get; set; }
        public string COURSE_SECTION_RANGE1 { get; set; }
    }
}
