//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class russData
    {
        public Nullable<int> TERM { get; set; }
        public Nullable<int> ID { get; set; }
        public string PLAN_CODE { get; set; }
        public string SUBJECT_CODE { get; set; }
        public string CATALOG_NUMBER { get; set; }
        public Nullable<int> CREDITS_TAKEN { get; set; }
    }
}
