//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FORM_BSW_CheckStatus
    {
        public string V1 { get; set; }
        public string V5 { get; set; }
        public Nullable<int> Status { get; set; }
        public bool CurrentMajor { get; set; }
        public bool SW205 { get; set; }
        public bool SW206 { get; set; }
        public bool Stats { get; set; }
        public bool comp71 { get; set; }
        public bool Trans1F { get; set; }
        public bool Trans1B { get; set; }
        public bool Trans1GPA { get; set; }
        public bool Trans2F { get; set; }
        public bool Trans2B { get; set; }
        public bool Trans2GPA { get; set; }
        public bool Trans3F { get; set; }
        public bool Trans3B { get; set; }
        public bool Trans3GPA { get; set; }
        public bool Trans4F { get; set; }
        public bool Trans4B { get; set; }
        public bool Trans4GPA { get; set; }
        public bool EssayCheck { get; set; }
        public bool SignCheck { get; set; }
        public bool LetterOfRec { get; set; }
        public Nullable<int> TotalUWCredits { get; set; }
        public Nullable<double> RecalcGPA { get; set; }
        public string LetterOfRec_Text { get; set; }
        public bool Accepted { get; set; }
        public bool letterSent { get; set; }
        public bool Denied { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
