//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FORM_BSWApplication_Transcript
    {
        public string V1 { get; set; }
        public string V2 { get; set; }
        public string V3 { get; set; }
        public string V4 { get; set; }
        public string V5 { get; set; }
        public string V6 { get; set; }
        public string V7 { get; set; }
        public string V8 { get; set; }
        public string V9 { get; set; }
        public string V10 { get; set; }
        public Nullable<int> Number { get; set; }
        public string InstName_1_ { get; set; }
        public string InstName_2_ { get; set; }
        public string InstName_3_ { get; set; }
        public string InstName_4_ { get; set; }
        public string InstName_5_ { get; set; }
        public string InstName_6_ { get; set; }
        public string InstGPA_1_ { get; set; }
        public string InstGPA_2_ { get; set; }
        public string InstGPA_3_ { get; set; }
        public string InstGPA_4_ { get; set; }
        public string InstGPA_5_ { get; set; }
        public string InstGPA_6_ { get; set; }
        public string TransFront_1_ { get; set; }
        public string TransFront_2_ { get; set; }
        public string TransFront_3_ { get; set; }
        public string TransFront_4_ { get; set; }
        public string TransFront_5_ { get; set; }
        public string TransFront_6_ { get; set; }
        public string NoBack_1_ { get; set; }
        public string NoBack_2_ { get; set; }
        public string NoBack_3_ { get; set; }
        public string NoBack_4_ { get; set; }
        public string NoBack_5_ { get; set; }
        public string NoBack_6_ { get; set; }
        public string TransBack_1_ { get; set; }
        public string TransBack_2_ { get; set; }
        public string TransBack_3_ { get; set; }
        public string TransBack_4_ { get; set; }
        public string TransBack_5_ { get; set; }
        public string TransBack_6_ { get; set; }
    }
}
