//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAsset
    {
        public int RecID { get; set; }
        public int AssetID { get; set; }
        public string AssetName { get; set; }
        public Nullable<int> AssetTypeID { get; set; }
        public Nullable<System.DateTime> AquisitionDate { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string Notes { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string SerialCode { get; set; }
        public string Program { get; set; }
        public string Site { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public string CPU { get; set; }
        public string RAM { get; set; }
        public string HDDCap { get; set; }
        public string DeepFreeze { get; set; }
        public Nullable<System.DateTime> ServiceUpdate { get; set; }
        public string ServiceUpdateNote { get; set; }
        public string ServiceUpdateUser { get; set; }
        public Nullable<bool> canCheckOut { get; set; }
        public string Funding { get; set; }
        public string inkType { get; set; }
    }
}
