//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContact_Log
    {
        public int contactID { get; set; }
        public Nullable<System.DateTime> sentDate { get; set; }
        public string toAddress { get; set; }
        public Nullable<int> contactTypeID { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> ADM_APPL_NUMBER { get; set; }
        public Nullable<int> TERM { get; set; }
        public string ExternalID { get; set; }
        public string queuedBy { get; set; }
        public Nullable<System.DateTime> queuedDate { get; set; }
        public int contactMethodID { get; set; }
        public string contactNote { get; set; }
        public string contactBy { get; set; }
        public string contactSubject { get; set; }
    
        public virtual tblLookupContact_Method tblLookupContact_Method { get; set; }
        public virtual tblLookupContact_Type tblLookupContact_Type { get; set; }
    }
}
