//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConcentration
    {
        public int RID { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> ConcID { get; set; }
        public string ConcNotes { get; set; }
        public Nullable<System.DateTime> ConcAdded { get; set; }
        public Nullable<System.DateTime> ConcUpdated { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
