//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExemptionGrid
    {
        public int ID { get; set; }
        public int entity_id { get; set; }
        public string Stats_EG { get; set; }
        public string Stats_Note { get; set; }
        public string c605_EG { get; set; }
        public string c605_Note { get; set; }
        public string c711_EG { get; set; }
        public string c711_Note { get; set; }
        public string c441_EG { get; set; }
        public string c441_Note { get; set; }
        public string c442_EG { get; set; }
        public string c442_Note { get; set; }
        public string c400_EG { get; set; }
        public string c400_Note { get; set; }
        public string c401_EG { get; set; }
        public string c401_Note { get; set; }
        public string c606_EG { get; set; }
        public string c606_Note { get; set; }
        public string c650_EG { get; set; }
        public string c650_note { get; set; }
        public string c640_EG { get; set; }
        public string c640_Note { get; set; }
        public bool formComplete { get; set; }
        public string Stats_IntNote { get; set; }
        public string c605_IntNote { get; set; }
        public string c711_IntNote { get; set; }
        public string c441_IntNote { get; set; }
        public string c442_IntNote { get; set; }
        public string c400_IntNote { get; set; }
        public string c401_IntNote { get; set; }
        public string c606_IntNote { get; set; }
        public string c650_IntNote { get; set; }
        public string c640_IntNote { get; set; }
        public Nullable<int> letterToSend { get; set; }
        public bool sendAgain { get; set; }
        public Nullable<bool> showGrid { get; set; }
        public Nullable<int> c711_WarrantCredits { get; set; }
        public Nullable<int> c440_WarrantCredits { get; set; }
        public Nullable<int> c441_WarrantCredits { get; set; }
        public Nullable<int> c442_WarrantCredits { get; set; }
        public Nullable<int> c400_WarrantCredits { get; set; }
        public Nullable<int> c401_WarrantCredits { get; set; }
        public Nullable<int> c606_WarrantCredits { get; set; }
        public Nullable<int> c650_WarrantCredits { get; set; }
        public Nullable<int> c640_WarrantCredits { get; set; }
        public Nullable<int> c605_WarrantCredits { get; set; }
        public string c612_EG { get; set; }
        public string c612_Note { get; set; }
        public Nullable<int> c612_WarrantCredits { get; set; }
        public string c612_IntNote { get; set; }
    }
}
