//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEntityform_type
    {
        public int id { get; set; }
        public string type { get; set; }
        public string label { get; set; }
        public Nullable<short> weight { get; set; }
        public string data { get; set; }
        public Nullable<short> status { get; set; }
        public string module { get; set; }
    }
}
