//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmail
    {
        public string PVI { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public Nullable<int> HR_EMPLID { get; set; }
        public int ISIS_EMPLID { get; set; }
        public byte[] upsize_ts { get; set; }
        public System.DateTime updated_date { get; set; }
        public int RID { get; set; }
    }
}
