//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFieldContact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFieldContact()
        {
            this.tblSupervisors = new HashSet<tblSupervisor>();
            this.tblWorkLocations = new HashSet<tblWorkLocation>();
        }
    
        public int FCID { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string WorkPhone { get; set; }
        public string WorkExtension { get; set; }
        public string Work2Phone { get; set; }
        public string Work2Extension { get; set; }
        public string CellPhone { get; set; }
        public string HomePhone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Email2 { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public bool Supervisor { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> ContactAdded { get; set; }
        public Nullable<System.DateTime> ContactUpdated { get; set; }
        public byte[] upsize_ts { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSupervisor> tblSupervisors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWorkLocation> tblWorkLocations { get; set; }
    }
}
