//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGrad_APPLICANTS
    {
        public int EMPLID { get; set; }
        public int TERM { get; set; }
        public string APPLICANTID { get; set; }
        public string CAMPUS_ID { get; set; }
        public int ADM_APPL_NBR { get; set; }
        public string LNAME { get; set; }
        public string FNAME { get; set; }
        public string MNAME { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<System.DateTime> SUBMITTED { get; set; }
        public Nullable<System.DateTime> EXPORTED { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED { get; set; }
        public Nullable<System.DateTime> SECAPP_SUBMITTED { get; set; }
    }
}
