//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGRAD_SUPLAPP_RESPONSES
    {
        public string APPID { get; set; }
        public double SECAPP_QUESTION_SEQ { get; set; }
        public string SECAPP_QUESTION { get; set; }
        public string SECAPP_ANSWER { get; set; }
    }
}
