//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGrad_APPS_Cleaning
    {
        public int RID { get; set; }
        public int ID { get; set; }
        public int ADMIT_TERM { get; set; }
        public Nullable<int> fallGrades { get; set; }
        public bool Essay { get; set; }
        public bool SupplementalApp { get; set; }
        public bool Letter { get; set; }
        public bool Transcript { get; set; }
        public bool SocScience30Cred { get; set; }
        public bool GPA60Cred { get; set; }
        public bool TOEFL { get; set; }
        public Nullable<int> hasBSW { get; set; }
        public Nullable<int> BSW5years { get; set; }
        public int ADM_APPL_NUMBER { get; set; }
        public string ACAD_PLAN { get; set; }
        public bool isAOF { get; set; }
        public Nullable<int> cohort { get; set; }
        public bool isIncomplete { get; set; }
        public string gradNote { get; set; }
    }
}
