//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGRAD_RATINGS
    {
        public Nullable<int> EMPLID { get; set; }
        public Nullable<int> TERM { get; set; }
        public string REVIEWER_NAME { get; set; }
        public string REVIEWER_NETID { get; set; }
        public Nullable<System.DateTime> EFFDT { get; set; }
        public Nullable<double> RANK_VALUE { get; set; }
        public string RANK_DESCR { get; set; }
        public string REVIEWER_NOTE { get; set; }
        public int RID { get; set; }
    }
}
