//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGrad_DECISION_SINGLE_FINAL
    {
        public double ID { get; set; }
        public Nullable<int> ADMIT_TERM { get; set; }
        public string ACAD_PROG { get; set; }
        public string PROG_REASON { get; set; }
    }
}
