//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLookupTerm
    {
        public int TERM { get; set; }
        public string TERM_DESCR { get; set; }
        public Nullable<System.DateTime> TERM_BEGIN_DATE { get; set; }
        public Nullable<System.DateTime> TERM_END_DATE { get; set; }
        public Nullable<System.DateTime> EXTRACT_DATE_TIME { get; set; }
    }
}
