//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLookupCourse_Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLookupCourse_Group()
        {
            this.tblLookupCourse_ORDER = new HashSet<tblLookupCourse_ORDER>();
            this.tblSTDNT_COURSES_GroupOveride = new HashSet<tblSTDNT_COURSES_GroupOveride>();
        }
    
        public int courseGroupID { get; set; }
        public string GroupTitle { get; set; }
        public bool canOverride { get; set; }
        public Nullable<int> currentProgram { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLookupCourse_ORDER> tblLookupCourse_ORDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSTDNT_COURSES_GroupOveride> tblSTDNT_COURSES_GroupOveride { get; set; }
    }
}
