//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLookupGroup
    {
        public int PTGID { get; set; }
        public string GroupName { get; set; }
        public int StartYear { get; set; }
        public Nullable<int> LabelProgram { get; set; }
        public Nullable<bool> isMSW { get; set; }
        public Nullable<bool> isFTMSW { get; set; }
        public Nullable<bool> isPTMSW { get; set; }
        public Nullable<bool> isBSW { get; set; }
        public Nullable<bool> isPHD { get; set; }
        public Nullable<bool> isAll { get; set; }
    }
}
