//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLookupFocusArea
    {
        public int FID { get; set; }
        public string Focus_DESC { get; set; }
        public Nullable<bool> isMSW { get; set; }
        public Nullable<bool> isPhD { get; set; }
        public Nullable<bool> isAll { get; set; }
        public Nullable<bool> isSpecial { get; set; }
    }
}
