//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoookup_579_Topics
    {
        public int TID { get; set; }
        public Nullable<int> TOPIC_TITLE_NUMBER { get; set; }
        public string CATALOG_NUMBER { get; set; }
    }
}
