//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNotification
    {
        public int NID { get; set; }
        public string noteTitle { get; set; }
        public string noteComment { get; set; }
        public string formName { get; set; }
        public string formFilter { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string createdBy { get; set; }
        public string noteFor { get; set; }
        public bool active { get; set; }
    }
}
