//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlacement
    {
        public int SPID { get; set; }
        public int OrgID { get; set; }
        public string Comments { get; set; }
        public int ID { get; set; }
        public int TERM { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> PlacementAdded { get; set; }
        public Nullable<System.DateTime> PlacementUpdated { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
