//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReview_COUNT_VIEW
    {
        public int ReviewerID { get; set; }
        public int TERM { get; set; }
        public Nullable<int> ReviewCount { get; set; }
        public bool canBSW { get; set; }
    }
}
