//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReview_Score_Override
    {
        public int ID { get; set; }
        public int TERM { get; set; }
        public int overrideScore { get; set; }
        public string Score_Note { get; set; }
        public int OverrideID { get; set; }
    }
}
