//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReviewers_TERM
    {
        public int ReviewerID { get; set; }
        public int RTID { get; set; }
        public int TERM { get; set; }
        public bool canFTMSW { get; set; }
        public bool canPTMSW_M { get; set; }
        public bool canPTMSW_E { get; set; }
        public bool canBSW { get; set; }
        public Nullable<int> maxReviews { get; set; }
        public bool ignoreMax { get; set; }
        public bool assignReviews { get; set; }
        public double assignmentFactor { get; set; }
        public bool canPHD { get; set; }
        public bool canFaculty { get; set; }
    
        public virtual tblReviewer tblReviewer { get; set; }
    }
}
