//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSupervisor
    {
        public int SupervisorID { get; set; }
        public int SPID { get; set; }
        public int FCID { get; set; }
        public Nullable<int> SupervisorTypeID { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public byte[] upsize_ts { get; set; }
    
        public virtual tblFieldContact tblFieldContact { get; set; }
    }
}
