//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSTDNT_PLAN
    {
        public Nullable<int> TERM { get; set; }
        public Nullable<int> ID { get; set; }
        public string ID_String { get; set; }
        public bool WITHDREW_IND { get; set; }
        public string CAREER { get; set; }
        public string ACADEMIC_PROGRAM_CODE { get; set; }
        public string PLAN_TYPE { get; set; }
        public string PLAN_CODE { get; set; }
        public string DEGREE_OBJECTIVE { get; set; }
        public Nullable<int> PLAN_GROUP { get; set; }
        public string CERTIFICATE_CODE { get; set; }
        public string PLAN_DESCR { get; set; }
        public string TRANSCRIPT_DESCR { get; set; }
        public Nullable<System.DateTime> PLAN_DECLARATION_DATE { get; set; }
        public string SUBPLAN_TYPE { get; set; }
        public string SUBPLAN_CODE { get; set; }
        public string SUBPLAN_DESCR { get; set; }
        public Nullable<System.DateTime> SUBPLAN_DECLARATION_DATE { get; set; }
        public Nullable<System.DateTime> EXTRACT_DATE_TIME { get; set; }
        public string keyField { get; set; }
    
        public virtual tblSTDNT_LOCAL tblSTDNT_LOCAL { get; set; }
    }
}
