//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSeminar
    {
        public int TERM { get; set; }
        public int ID { get; set; }
        public Nullable<double> CAMPUS_ID { get; set; }
        public string COURSE_ID { get; set; }
        public string CATALOG_NUMBER { get; set; }
        public string COURSE_SECTION_RANGE1 { get; set; }
        public string SUBJECT_CODE { get; set; }
        public string OFFICIAL_GRADE { get; set; }
    }
}
