//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSTDNT_PHD
    {
        public int PHDID { get; set; }
        public int ID { get; set; }
        public Nullable<int> compCoursework_TERM { get; set; }
        public Nullable<int> compDissertatorStatus_TERM { get; set; }
        public Nullable<int> startOfProgram_TERM { get; set; }
        public string Advisor { get; set; }
        public Nullable<bool> inResidence { get; set; }
        public string officeLoc { get; set; }
        public Nullable<int> GauranteeExpires { get; set; }
        public Nullable<System.DateTime> compPrelimProposal_DATE { get; set; }
        public Nullable<System.DateTime> compPrelim_DATE { get; set; }
        public Nullable<System.DateTime> compDissertationProposal_DATE { get; set; }
        public Nullable<System.DateTime> compDissertation_DATE { get; set; }
    }
}
