//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSTDNT_Address
    {
        public int AddrID { get; set; }
        public int ID { get; set; }
        public string AddrStreet { get; set; }
        public string AddrCity { get; set; }
        public string AddrState { get; set; }
        public string AddrZipCode { get; set; }
        public string AddrCountry { get; set; }
        public int AddrTypeID { get; set; }
        public System.DateTime AddrUpdate { get; set; }
    
        public virtual tblLookupAddress_Types tblLookupAddress_Types { get; set; }
        public virtual tblSTDNT_Address tblSTDNT_Address1 { get; set; }
        public virtual tblSTDNT_Address tblSTDNT_Address2 { get; set; }
        public virtual tblSTDNT_LOCAL tblSTDNT_LOCAL { get; set; }
    }
}
