//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSTDNT_FLAG
    {
        public int RID { get; set; }
        public int ID { get; set; }
        public int flagID { get; set; }
        public string flagNote { get; set; }
    
        public virtual tblLookupFlag tblLookupFlag { get; set; }
        public virtual tblSTDNT_LOCAL tblSTDNT_LOCAL { get; set; }
    }
}
