//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUGRD_Decisions
    {
        public double ID { get; set; }
        public string APPLICATION_NUMBER { get; set; }
        public string PROGRAM_ACTION { get; set; }
        public string PROGRAM_ACTION_DESCR { get; set; }
        public System.DateTime PROGRAM_ACTION_DATE { get; set; }
        public string PROGRAM_REASON { get; set; }
        public string PROGRAM_REASON_DESCR { get; set; }
        public Nullable<System.DateTime> EXTRACT_DATE_TIME { get; set; }
    }
}
