//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUGRD_APPS
    {
        public Nullable<double> ID { get; set; }
        public string ID_string { get; set; }
        public string APPLICATION_NUMBER { get; set; }
        public string APPLIC_SOURCE { get; set; }
        public string CAMPUS_ID { get; set; }
        public string LAST_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string GENDER { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public string COUNTRY_OF_BIRTH_CODE { get; set; }
        public string COUNTRY_OF_BIRTH_DESCR { get; set; }
        public string ETHNIC_GROUP { get; set; }
        public string ETHNIC_GROUP_DESCR_SHORT { get; set; }
        public string TARGETED_MINORITY { get; set; }
        public string ALUMNI_TIE_IND { get; set; }
        public string RELEASE_TO_ALUMNI_IND { get; set; }
        public string VISA_PERMIT_TYPE { get; set; }
        public string CITIZENSHIP { get; set; }
        public string CITIZEN_STATUS { get; set; }
        public string CITIZEN_STATUS_DESCR { get; set; }
        public string COUNTRY_CITIZENSHIP_CODE { get; set; }
        public string COUNTRY_CITIZENSHIP_DESCR { get; set; }
        public string RESIDENCY_CODE { get; set; }
        public Nullable<System.DateTime> RESIDENCY_DATE { get; set; }
        public string TUITION_RESIDENCY_CODE { get; set; }
        public string VETERANS_STATUS { get; set; }
        public string ATHL_CATEGORY { get; set; }
        public string ATHL_CATEGORY_DESCR { get; set; }
        public string HOLD_POSTAL_IND { get; set; }
        public string HOLD_EMAIL_IND { get; set; }
        public string HOME_ADDRESS_LINE1 { get; set; }
        public string HOME_ADDRESS_LINE2 { get; set; }
        public string HOME_ADDRESS_LINE3 { get; set; }
        public string HOME_ADDRESS_LINE4 { get; set; }
        public string HOME_ADDRESS_CITY { get; set; }
        public string HOME_ADDRESS_STATE { get; set; }
        public string HOME_ADDRESS_ZIP_CODE { get; set; }
        public string HOME_COUNTY_DESCR { get; set; }
        public string HOME_COUNTRY_CODE { get; set; }
        public string HOME_COUNTRY_DESCR { get; set; }
        public string HOME_PHONE1 { get; set; }
        public string MAIL_ADDR_LINE1 { get; set; }
        public string MAIL_ADDR_LINE2 { get; set; }
        public string MAIL_ADDR_LINE3 { get; set; }
        public string MAIL_ADDR_LINE4 { get; set; }
        public string MAIL_ADDR_CITY { get; set; }
        public string MAIL_ADDR_STATE { get; set; }
        public string MAIL_ADDRESS_ZIP_CODE { get; set; }
        public string MAIL_COUNTRY_CODE { get; set; }
        public string MAIL_COUNTRY_DESCR { get; set; }
        public string MAIL_PHONE1 { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public Nullable<System.DateTime> APPLIC_RECVD_DATE { get; set; }
        public string APPLIC_ADMIT_TERM { get; set; }
        public string APPLIC_ADMIT_TYPE { get; set; }
        public string ADMIT_TYPE_DESCR { get; set; }
        public Nullable<System.DateTime> APPLIC_CREATE_DATE { get; set; }
        public string PRIMARY_ACADEMIC_GROUP { get; set; }
        public string APPLIC_ACADEMIC_PROGRAM { get; set; }
        public string APPLIC_ACADEMIC_PLAN { get; set; }
        public string APPLIC_ACADEMIC_LEVEL { get; set; }
        public string APPLIC_PROGRAM_STATUS { get; set; }
        public string PROGRAM_STATUS_DESCR { get; set; }
        public string STUDENT_GROUP { get; set; }
        public string STUDENT_GROUP_DESCR { get; set; }
        public string APPLIC_RECRUITER_ID { get; set; }
        public string RECRUITER_NAME { get; set; }
        public string ADVISOR_NAME { get; set; }
        public string ADVISOR_DEPT { get; set; }
        public string APPLIC_FIN_AID_INTEREST { get; set; }
        public string APPLIC_FEE_TYPE { get; set; }
        public Nullable<decimal> APPLIC_FEE_PAID { get; set; }
        public Nullable<System.DateTime> APPLIC_FEE_DATE { get; set; }
        public string APPLIC_FEE_STATUS { get; set; }
        public string PROGRAM_ACTION { get; set; }
        public Nullable<System.DateTime> PROGRAM_ACTION_DATE { get; set; }
        public string PROGRAM_ACTION_DESCR { get; set; }
        public string PROGRAM_REASON { get; set; }
        public string PROGRAM_REASON_DESCR { get; set; }
        public Nullable<System.DateTime> EXTRACT_DATE_TIME { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
