//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Grad_Apps_New_Students
    {
        public double ID { get; set; }
        public string CAMPUS_ID { get; set; }
        public string LAST_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public int ADM_APPL_NBR { get; set; }
        public int ADMIT_TERM { get; set; }
        public string ACAD_PLAN { get; set; }
        public string ACAD_SUBPLAN { get; set; }
    }
}
