//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewPTPAdmissionData
    {
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public int ADMIT_TERM { get; set; }
        public string ACAD_PLAN { get; set; }
        public string ACAD_SUBPLAN { get; set; }
        public string PROG_ACTION { get; set; }
        public string PROG_REASON { get; set; }
        public Nullable<System.DateTime> SUBMITTED { get; set; }
        public Nullable<System.DateTime> SECAPP_SUBMITTED { get; set; }
        public string MATERIALS_COMPLETED { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public int isTransfer { get; set; }
    }
}
