//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Seminar_Students
    {
        public int UG { get; set; }
        public int TERM { get; set; }
        public int ID { get; set; }
        public string FullName { get; set; }
        public Nullable<int> SWMailbox { get; set; }
        public string CurrentStreet { get; set; }
        public string CurrentAddress2 { get; set; }
        public string CellPhone { get; set; }
        public string WorkPhone { get; set; }
        public string HomePhone { get; set; }
        public string CATALOG_NUMBER { get; set; }
        public string COURSE_SECTION_RANGE1 { get; set; }
        public string COURSE_TITLE { get; set; }
        public string TERM_DESCR { get; set; }
        public string Heading { get; set; }
        public bool AdvSt { get; set; }
        public string WorkPhoneExtension { get; set; }
        public string HomePhoneExtension { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string LName { get; set; }
        public Nullable<double> CAMPUS_ID { get; set; }
    }
}
