//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewCompletedForm
    {
        public int ID { get; set; }
        public string CondEthics { get; set; }
        public string DutyDisclose { get; set; }
        public string ExemptionGrid { get; set; }
        public string FieldPreference { get; set; }
        public string MSWConfirmation { get; set; }
        public string PlacementConfirmation { get; set; }
        public string Plagiarism { get; set; }
        public string Declaration { get; set; }
        public string FocusAreaDeclaration { get; set; }
        public string StudentRights { get; set; }
        public string RequiredForms { get; set; }
    }
}
